version: "3"

services:
  frontend:
    build: ./front-end
    container_name: frontend-challenge
    restart: always
    working_dir: /app
    depends_on:
      - backend
    volumes:
      - ./front-end:/app
    ports:
      - "3000:3000"
    networks:
      - search_api_net

  backend:
    build: ./back-end
    container_name: backend-challenge
    tty: true
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ./back-end:/app
    depends_on:
      - db
    ports:
      - 3030:3001
      - 3006:3006
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      API_HOST: 'node'
      API_PORT: 3030
      NODE_ENV: 'development'
    networks:
      - search_api_net

  db:
    container_name: blogs_api_db
    image: mysql:8.0.23
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - search_api_net


networks:
  search_api_net:
    driver: bridge
